---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: translator-backendconfig
spec:
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 90

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev-translator-backend
  name: dev-translator-backend
  namespace: dev-translator
spec:
  selector:
    matchLabels:
      app: dev-translator-backend
  template:
    metadata:
      labels:
        app: dev-translator-backend
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/xplor-sunbird-rc/dev-translator/xplor-ai-services-translator:latest
        imagePullPolicy: Always
        name: dev-translator-backend
        resources:
          requests:
            cpu: "500m"
            memory: "4000Mi"
          limits:
            cpu: "1000m" 
            memory: "6000Mi"
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: translator-autoscaling
  name: translator-autoscaling
  namespace: dev-translator
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-translator-backend
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev-translator-backend
  name: translator-svc
  namespace: dev-translator
  annotations:
    cloud.google.com/backend-config: '{"ports": {"5000":"translator-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 5000
    targetPort: 8000
    protocol: TCP
  selector:
    app: dev-translator-backend
  type: NodePort
